### ISSUE TITLE
problem opening  CO-xp.owl file in Protege (v.4.3)

### ISSUE THREAD

**Issue by cooperl09** [Planteome/ibp-crossproducts#1]
I was not able to open the CO-xp.owl file in Protege (v.4.3) this morning.  See attached screen of error message. Thx
says: org.xml.sax.SAXParseException: White spaces are required between publicId and systemId.

![screen shot 2015-09-03 at 11 34 59 am](https://cloud.githubusercontent.com/assets/7378000/9667348/1a59ca62-5230-11e5-80e3-161b90bd8eaf.png)

**Comment by ramonawalls** [comment]
You will probably have to switch to Protege 5. This problem happens with Protege 4 when you try to open a file with a PURL that redirects to Github, because Github uses https.

**Comment by marieALaporte** [comment]
An other solution would be that you use a local version of the file. 
I was not aware of this problem in Protégé 4 since I am using Protégé 5.

**Comment by cooperl09** [comment]
Thanks, i will give it a try.  I actually did try to open from my local file.  will try 5.0
